name: Deploy Next.js to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to Server
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
